src/VecSim/vecsim.h
tests/unit/test_hnswlib.cpp

https://app.circleci.com/pipelines/github/RediSearch/RediSearch/4407/workflows/1fa96178-58c9-42e8-a24e-f36ac8892193/jobs/27143

fix compilation error

---

src/VecSim/algorithms/hnsw/hnswlib.h
src/VecSim/utils/arr_cpp.h
tests/unit/test_hnswlib.cpp

Minor fixes due to problems detected in valgrind memcheck

fix valgrind memory leaks

---

src/CMakeLists.txt

@rafie please see here https://github.com/xianyi/OpenBLAS#support-for-multiple-targets-in-a-single-library

multiarch build

---

src/VecSim/vecsim.cpp

Use VecSimIndex_TopKQuery by VecSimIndex_TopKQueryByID

---

src/VecSim/query_results.h

Needed for RediSearch:
https://app.circleci.com/pipelines/github/RediSearch/RediSearch/5902/workflows/a80017c6-690f-4616-9052-7b70cb0d0b0a/jobs/32633

include stdbool.h for C linkage

---

.circleci/config.yml
pyproject.toml
src/VecSim/memory/vecsim_malloc.h
src/VecSim/vec_sim_common.h
tests/module/CMakeLists.txt
tests/module/flow/test_vecsim_malloc.py
tests/module/memory_test.c
tox.ini

added a module for testing that memory allocating in redis-server is preformed by the server allocator.
added automation for running the module and added it to tox tests for testing the allocating process from the CI

Redis memory test

---

src/VecSim/algorithms/hnsw/hnswlib.h
src/VecSim/vec_sim.cpp
tests/unit/test_hnswlib.cpp

to detect parameter overflow, and that M != 1

added parameter check

---

notebooks/HNSWLIB_Sanity.ipynb
src/VecSim/algorithms/brute_force/brute_force.cpp
src/VecSim/algorithms/brute_force/brute_force.h
src/VecSim/algorithms/hnsw/hnswlib.h
src/VecSim/algorithms/hnsw/hnswlib_c.cpp
src/VecSim/algorithms/hnsw/hnswlib_c.h
src/VecSim/vec_sim.cpp
src/VecSim/vec_sim_common.h
src/VecSim/vec_sim_index.h
src/python_bindings/bindings.cpp
tests/benchmark/bf_google_benchmark.cpp
tests/flow/test_bruteforce.py
tests/flow/test_hnswlib.py
tests/module/memory_test.c
tests/unit/test_allocator.cpp
tests/unit/test_bruteforce.cpp
tests/unit/test_hnswlib.cpp

now every algorithm has its own parameters
also changed .size argument to .dim

VecSim params struct update

---

src/VecSim/algorithms/hnsw/hnswlib_c.cpp
tests/unit/test_hnswlib.cpp

bug for when legal prefix parameter is passed

bug fix and test update

---

src/VecSim/algorithms/brute_force/brute_force.cpp
src/VecSim/algorithms/brute_force/brute_force.h
src/VecSim/algorithms/hnsw/hnsw_wrapper.cpp
src/VecSim/algorithms/hnsw/hnsw_wrapper.h
src/VecSim/vec_sim.cpp
src/VecSim/vec_sim.h
tests/unit/test_bruteforce.cpp
tests/unit/test_hnswlib.cpp

added this function for estimating the size of a vector index before creating it

added `VecSimIndex_EstimateInitialSize()` function

---

src/VecSim/algorithms/brute_force/brute_force.cpp
src/VecSim/algorithms/brute_force/brute_force.h
src/VecSim/algorithms/hnsw/hnsw_wrapper.cpp
src/VecSim/algorithms/hnsw/hnsw_wrapper.h
src/VecSim/vec_sim.cpp
src/VecSim/vec_sim.h
src/VecSim/vec_sim_common.h
tests/unit/test_bruteforce.cpp
tests/unit/test_hnswlib.cpp

added a function to return expected element memory consumption according to the given parameters, including metadata for it.

Get estimated memory consumption of an element

---

.circleci/config.yml
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

1. #...
2. MOD...
1. ...
2. ...

Pull request template

---

sbin/system-setup.py

1. #...
2. MOD...
1. ...
2. ...

Removin gunused dependencies, in order to fix the build

---

src/VecSim/algorithms/hnsw/hnsw_batch_iterator.cpp
src/VecSim/algorithms/hnsw/hnswlib.h

Missing include file made some optimizations always disabled.

Bug hnsw prefetch

---

Makefile
src/VecSim/spaces/IP/IP_AVX.cpp
src/VecSim/spaces/IP/IP_AVX512.cpp
src/VecSim/spaces/IP/IP_AVX512.h
src/VecSim/spaces/IP/IP_SSE.cpp
src/VecSim/spaces/IP_space.cpp
src/VecSim/spaces/L2/L2_AVX.cpp
src/VecSim/spaces/L2/L2_AVX.h
src/VecSim/spaces/L2/L2_AVX512.cpp
src/VecSim/spaces/L2/L2_AVX512.h
src/VecSim/spaces/L2/L2_SSE.cpp
src/VecSim/spaces/L2_space.cpp
src/VecSim/spaces/space_includes.h
tests/benchmark/CMakeLists.txt
tests/benchmark/bm_spaces.cpp
tests/unit/test_spaces.cpp

* improving functions
* improving logic of optimization choosing
* first metrics benchmark
* improved benchmark
* added tests for all new functions
* improved benchmark and added comments
* added logic explanation
* fixing alignment
* added bm_spaces to "make benchmark" run
* added arch check in compile time
* refactor benchmark file
* comment fix

Space Optimization Fix (#175)

---

src/VecSim/algorithms/brute_force/brute_force.cpp
src/VecSim/algorithms/hnsw/hnsw_wrapper.cpp
src/VecSim/algorithms/hnsw/hnswlib.h
tests/unit/test_bruteforce.cpp
tests/unit/test_hnswlib.cpp

* modified resize logic of BF addvector so that the ids2vectors mapping size fits blockSize
* fixed increasing count in case od re-using id, update brute_force_reindexing_same_vector test
* clang format
* HNSWIndex::addVector aligns the capacity to block size, HNSWIndex::deleteVector in case an entire block is removed, the capacity is aligned to blocksize and a decreased by block size, added test for resize cases in hnswlib
* make format
* update size estimation test
* fixed after Alon's review
* clang format
* cahnged hnsw::remove point to return false in case not found,
also changed HNSWIndex::delete vector to return false in this case (before checking if resizing is required) - this covers (hopedully) also empty index case and resizing only when actual deletion happend
* added tests …

resizing to align blocksize  (#177)

---

tests/unit/test_hnswlib.cpp

As a follow up for @meiravgri PR that found a bug in brute force algorithm (#178), I add a test for checking that HNSW move blobs correctly on updates

added sanity test for updating vector in HNSW algo

---

.circleci/config.yml
tests/unit/test_hnswlib.cpp

* added sanity test for updating vector in HNSW algorithm
* improved test
* comment fix

added sanity test for updating vector in HNSW algo (#190)

---

.circleci/config.yml
.github/workflows/perf.yml
Makefile
cmake/gtest.cmake
src/VecSim/algorithms/brute_force/brute_force.cpp
src/VecSim/algorithms/brute_force/brute_force.h
src/VecSim/algorithms/hnsw/hnsw_wrapper.cpp
src/VecSim/algorithms/hnsw/hnsw_wrapper.h
src/VecSim/algorithms/hnsw/hnswlib.h
src/VecSim/utils/vec_utils.cpp
src/VecSim/utils/vec_utils.h
src/VecSim/vec_sim_common.h
src/python_bindings/bindings.cpp
tests/benchmark/CMakeLists.txt
tests/benchmark/bm_basics.cpp
tests/benchmark/bm_batch_iterator.cpp
tests/benchmark/bm_updated_index.cpp
tests/benchmark/bm_utils.cpp
tests/benchmark/bm_utils.h
tests/benchmark/data/hnsw_indices.txt
tests/flow/test_hnswlib.py
tests/unit/test_bruteforce.cpp
tests/unit/test_hnswlib.cpp
tests/unit/test_utils.cpp
tox.ini

Add HNSW range + benchmark dashboards to 0.4 [cherry-pick]

---

.github/release-drafter-config.yml

this is an attempt to support multiple branch based release patterns
1. #...
2. MOD...
1. ...
2. ...

Muliple branch based releases #1: main branch

---

src/CMakeLists.txt
src/VecSim/algorithms/brute_force/bf_batch_iterator.cpp
src/VecSim/algorithms/brute_force/bf_batch_iterator.h
src/VecSim/algorithms/brute_force/brute_force.cpp
src/VecSim/algorithms/brute_force/brute_force.h
src/VecSim/algorithms/brute_force/brute_force_single.cpp
src/VecSim/algorithms/brute_force/brute_force_single.h
src/VecSim/algorithms/brute_force/vector_block.h
src/VecSim/algorithms/hnsw/hnsw_batch_iterator.cpp
src/VecSim/algorithms/hnsw/hnsw_wrapper.cpp
src/VecSim/algorithms/hnsw/hnsw_wrapper.h
src/VecSim/algorithms/hnsw/hnswlib.h
src/VecSim/algorithms/hnsw/serialization.cpp
src/VecSim/info_iterator.h
src/VecSim/utils/vec_utils.cpp
src/VecSim/utils/vec_utils.h
src/VecSim/vec_sim.cpp
src/VecSim/vec_sim.h
src/VecSim/vec_sim_common.h
src/VecSim/vec_sim_index.cpp
src/VecSim/vec_sim_index.h
src/VecSim/vec_sim_interface.h
src/python_bindings/bindings.cpp
tests/benchmark/bm_basics.cpp
tests/unit/test_allocator.cpp
tests/unit/test_bruteforce.cpp
tests/unit/test_hnswlib.cpp
tests/unit/test_utils.cpp

**The changes in the pull request**
This is the first step for supporting multi-value indexing for vectors. It is focused mostly on the base vecsim index and the FLAT algorithm. Another PR will set the final changes in the HNSW algorithm.
No test in this PR, as it does not add any logic. The fact that all existing tests are passing shows the completeness of this PR. Additional tests will be added soon and will fix the coverage hit
1. modifies all index classes, making them ready for more derived classes in the future.
2. changes the inheritance tree for the brute force algorithm and its batch iterator to support multi-value brute force indexing.
3. prepares the entire inheritance tree to support templating the algorithms.

Inheritance Refactor

---

src/CMakeLists.txt
src/VecSim/algorithms/brute_force/brute_force.cpp
src/VecSim/algorithms/brute_force/brute_force.h
src/VecSim/algorithms/brute_force/brute_force_factory.cpp
src/VecSim/algorithms/brute_force/brute_force_factory.h
src/VecSim/algorithms/hnsw/hnsw_factory.cpp
src/VecSim/algorithms/hnsw/hnsw_factory.h
src/VecSim/algorithms/hnsw/hnsw_wrapper.cpp
src/VecSim/algorithms/hnsw/hnsw_wrapper.h
src/VecSim/vec_sim.cpp
tests/unit/test_allocator.cpp

Index factory purpose is to manage creation and info index functions.
As we have and will elaborte to support more index configuration, 
we decide to create an independent class that will manage "logistics".
The functionalities currently moved from the index classes to the factory classes are:
* Allocation new index
* Supply memory info like initial size or element size.
1. Dependency of the base class on its inherited class
1. Indexes internal factory and memory estimation functions

Index factory

---

.github/release-drafter-config.yml

1. #...
2. MOD...
1. ...
2. ...

Muliple branch based releases #2: 0.3 branch

---

src/VecSim/algorithms/brute_force/bf_batch_iterator.cpp
src/VecSim/algorithms/brute_force/brute_force.cpp
src/VecSim/algorithms/brute_force/brute_force.h
src/VecSim/algorithms/brute_force/brute_force_multi.cpp
src/VecSim/algorithms/brute_force/brute_force_multi.h
src/VecSim/algorithms/brute_force/brute_force_single.h
src/VecSim/algorithms/hnsw/hnsw_batch_iterator.h
src/VecSim/algorithms/hnsw/hnswlib.h
src/VecSim/utils/updatable_heap.h
src/VecSim/utils/vecsim_stl.h
tests/unit/test_bruteforce_multi.cpp
tests/unit/test_common.cpp
tests/unit/test_utils.cpp

This PR enables KNN search with multivalue indexing. the returned results should have each label result at most once.
1. Defined abstract max priority queue class.
2. Changed the current definition of the max priority queue to derive from the abstract class.
3. Implemented updatable max heap.
4. Made the multi-value BF use this heap.
5. Generalize the BF base flow to support both heaps.

FLAT multivalue knn search implementation

---

src/VecSim/algorithms/brute_force/bf_batch_iterator.cpp

change the type of TopCandidatesIndices from `<size_t, size_t>` to `<labelType, size_t>`
None
None

changed TopCandidatesIndices type

---

src/VecSim/algorithms/brute_force/brute_force.h
src/VecSim/algorithms/brute_force/brute_force_multi.h
src/VecSim/algorithms/brute_force/brute_force_single.h
src/VecSim/algorithms/hnsw/hnsw.h
src/VecSim/utils/vec_utils.cpp
src/VecSim/utils/vec_utils.h
src/VecSim/vec_sim.cpp
src/VecSim/vec_sim_index.h
tests/unit/test_common.cpp

added static templated normalize vector function in VecSimAbstract.
1.Generelize normalize function
1. VecSimAbstract
2. removed normalize function from utils

added templated normalize function

---

src/VecSim/spaces/CMakeLists.txt
src/VecSim/spaces/IP/IP_SSE.h
src/VecSim/spaces/IP/IP_SSE_FP32.cpp
src/VecSim/spaces/IP/IP_SSE_FP64.cpp
src/VecSim/spaces/IP_space.cpp
src/VecSim/spaces/L2/L2_SSE_FP64.cpp
tests/unit/test_spaces.cpp

In this PR we added fp64 support to **inner product distance** calculation functions using **SSE optimization**

Fp64 dist func sse ip

---

src/VecSim/algorithms/brute_force/brute_force.h
src/VecSim/algorithms/brute_force/brute_force_multi.h
src/VecSim/algorithms/brute_force/brute_force_single.h
src/VecSim/algorithms/hnsw/hnsw.h
src/VecSim/algorithms/hnsw/hnsw_batch_iterator.h
src/VecSim/algorithms/hnsw/hnsw_factory.cpp
src/VecSim/algorithms/hnsw/hnsw_factory.h
src/VecSim/algorithms/hnsw/hnsw_multi.h
src/VecSim/algorithms/hnsw/hnsw_multi_batch_iterator.h
src/VecSim/algorithms/hnsw/hnsw_single.h
src/VecSim/algorithms/hnsw/hnsw_single_batch_iterator.h
src/VecSim/query_results.cpp
src/VecSim/utils/vecsim_stl.h
src/VecSim/vec_sim_interface.h
tests/unit/test_hnsw.cpp
tests/unit/test_hnsw_multi.cpp

This PR includes the implementation of the HNSW-multi batch-iterator. 
1. `hnsw_batch_iterator` is now a base for `hnsw_single_batch_iterator` and `hnsw_multi_batch_iterator`.
2. moved the creation of batch iterator from `hnsw_factory.cpp` to the derived classes hnsw_single and hnsw_multi.

Multivalue HNSW - implement batch iterator

---

src/VecSim/spaces/CMakeLists.txt
src/VecSim/spaces/L2/L2_AVX.h
src/VecSim/spaces/L2/L2_AVX_FP32.cpp
src/VecSim/spaces/L2/L2_AVX_FP64.cpp
src/VecSim/spaces/L2_space.cpp
tests/unit/test_spaces.cpp

In this PR we added fp64 support to **euclidean distance** calculation functions using **AVX optimization**

 L2 AVX support for fp64

---

src/VecSim/algorithms/brute_force/brute_force.h
src/VecSim/algorithms/brute_force/brute_force_multi.h
src/VecSim/algorithms/brute_force/brute_force_single.h
src/VecSim/algorithms/hnsw/hnsw.h
src/VecSim/algorithms/hnsw/hnsw_multi.h
src/VecSim/algorithms/hnsw/hnsw_single.h
src/VecSim/query_results.cpp
src/VecSim/query_results.h
src/VecSim/utils/vec_utils.cpp
src/VecSim/utils/vec_utils.h
src/VecSim/utils/vecsim_results_container.h
src/VecSim/vec_sim.cpp
src/VecSim/vec_sim.h
src/VecSim/vec_sim_common.h
src/VecSim/version.h
tests/flow/test_bruteforce.py
tests/flow/test_hnswlib.py
tests/unit/test_bruteforce.cpp
tests/unit/test_bruteforce_multi.cpp
tests/unit/test_common.cpp
tests/unit/test_hnsw.cpp
tests/unit/test_hnsw_multi.cpp
tests/unit/test_utils.cpp
tests/unit/test_utils.h

version 0.5.0

---

src/VecSim/algorithms/hnsw/hnsw.h
tests/unit/test_bruteforce.cpp

I also added an assert in hnsw delete flow

Test top-0 case for FLAT

---

Makefile

revisit makefile build rules
1. MOD-4313
1. ...
2. ...

revisit makefile MOD-4313

---

src/VecSim/algorithms/brute_force/bf_batch_iterator.h
src/VecSim/algorithms/brute_force/brute_force.h
src/VecSim/algorithms/hnsw/hnsw.h
src/VecSim/algorithms/hnsw/hnsw_batch_iterator.h
src/VecSim/vec_sim_common.h

Improving the readability of timeout callback calls.

Improving timeout callback call readability 

---

.github/workflows/multi-build.yml
.github/workflows/nightly.yml

1. #...
2. MOD...
1. ...
2. ...

fixed nightly flow

---

README.md

1. #...
2. MOD...
1. ...
2. ...

add GH actions + remove Circle + LGTM

---

.github/workflows/default_invoker.yml

This PR adds CI to feature branches
1. #...
2. MOD...
1. ...
2. ...

add feature branch to default flow invoker

---

src/VecSim/algorithms/hnsw/hnsw.h
src/VecSim/algorithms/hnsw/hnsw_batch_iterator.h
src/VecSim/algorithms/hnsw/hnsw_factory.cpp
src/VecSim/algorithms/hnsw/hnsw_serializer.h
src/VecSim/algorithms/hnsw/visited_nodes_handler.cpp
src/VecSim/algorithms/hnsw/visited_nodes_handler.h
src/VecSim/memory/vecsim_malloc.cpp
src/VecSim/memory/vecsim_malloc.h
src/VecSim/vec_sim_common.h
src/python_bindings/bindings.cpp
tests/unit/test_hnsw.cpp
tests/unit/test_hnsw_multi.cpp

Allow parallelism in *READ* operation only, by letting this PR stand alone without the whole "tiered HNSW" feature

Support parallel graph scans in HNSW - CP to main

---

.github/workflows/benchmark-labeled.yml

Added a condition to the bm_invoker job that checks if a benchmark label was intrigged.
1. bm_invoker runs for every label
1.benchmark-labeled.yml

fix bm invoker

---

src/VecSim/algorithms/hnsw/hnsw.h

In the parallel insert/search test we see that sometimes one of the vectors in the expected results doesn't appear in the query results, even though we make sure that all the vectors which are the expected results for the query are inserted *before* the query threads strat running. 
The reason for the flakiness is that we first insert a new label into the labels lookup, and only after we set the corresponding internal id as IN_PROCESS. When we make sure that the result vectors exist, we check that its label exists in the labels lookup, and that the id is NOT in process. However, there may be a situation where the vector is in the label lookup, but hasn't been set as in process yet. 
Hence, the fix is setting the vector IN_PROCES flag before the insertion to the label lookup.

Fix flaky parallel insert/search test HNSW

---

.github/workflows/arm.yml

1. #...
2. MOD...
1. ...
2. ...

larger arm machine

---

tests/unit/test_utils.h

1. #...
2. MOD...
1. ...
2. ...

remove fp64 from tiered index tests

---

CMakeLists.txt

1. #...
2. MOD...
1. ...
2. ...

update google benchmark to the latest version

---

.gitignore
src/VecSim/algorithms/hnsw/hnsw.h
tests/benchmark/bm_datasets.py
tests/benchmark/data/hnsw_indices/ hnsw_indices_updated.txt
tests/benchmark/data/hnsw_indices/hnsw_indices_all.txt
tests/benchmark/data/hnsw_indices/hnsw_indices_ann.txt
tests/benchmark/data/hnsw_indices/hnsw_indices_basic_fp32.txt
tests/benchmark/data/hnsw_indices/hnsw_indices_basic_fp64.txt
tests/benchmark/data/serializer.py
tests/benchmark/run_files/bm_basics_multi_fp32.cpp
tests/benchmark/run_files/bm_basics_multi_fp64.cpp
tests/benchmark/run_files/bm_basics_single_fp32.cpp
tests/benchmark/run_files/bm_basics_single_fp64.cpp
tests/benchmark/run_files/bm_batch_iterator_multi_fp32.cpp
tests/benchmark/run_files/bm_batch_iterator_multi_fp64.cpp
tests/benchmark/run_files/bm_batch_iterator_single_fp32.cpp
tests/benchmark/run_files/bm_batch_iterator_single_fp64.cpp
tests/benchmark/run_files/bm_updated_index_single_fp32.cpp

Update benchmarks to use new serialization files, made final decisions on the implementation of `processCandidate` and `processCandidate_Range`, uploaded a serialization script to the repo

HNSW Refactor - benchmarks - [MOD-5371]

---

src/VecSim/algorithms/hnsw/hnsw.h
src/VecSim/algorithms/hnsw/hnsw_serializer.h
tests/benchmark/bm_vecsim_general.h
tests/unit/test_hnsw_multi.cpp
tests/unit/test_hnsw_tiered.cpp

Renaming all kinds of variable names that contain "meta" to reduce confusion

Renaming "meta" variables

---

src/VecSim/algorithms/hnsw/hnsw.h
src/VecSim/algorithms/hnsw/hnsw_serializer.h
src/VecSim/algorithms/hnsw/hnsw_tiered.h
src/VecSim/utils/vec_utils.cpp
src/VecSim/utils/vec_utils.h
src/VecSim/vec_sim_common.h
src/VecSim/vec_sim_index.h
src/VecSim/vec_sim_interface.cpp
src/VecSim/vec_sim_tiered_index.h
tests/unit/CMakeLists.txt
tests/unit/test_common.cpp
tests/unit/test_hnsw_tiered.cpp

Add log level to our log messages and callback. Use "verbose" for the existing logs and add some more messages regarding capacity changes. + tiny fix in a test to reduce flakiness.

Logs extension

---

src/VecSim/algorithms/hnsw/hnsw.h
src/VecSim/algorithms/hnsw/hnsw_serializer.h
src/VecSim/algorithms/hnsw/hnsw_tiered.h
src/VecSim/utils/vec_utils.cpp
src/VecSim/utils/vec_utils.h
src/VecSim/vec_sim_common.h
src/VecSim/vec_sim_index.h
src/VecSim/vec_sim_interface.cpp
src/VecSim/vec_sim_tiered_index.h
tests/unit/CMakeLists.txt
tests/unit/test_common.cpp
tests/unit/test_hnsw_tiered.cpp

Logs extension (#408)

---

src/VecSim/algorithms/hnsw/hnsw.h
src/VecSim/utils/vec_utils.h

Postponing distance calculation in connections-repairing flows and performing them only if needed.
In the average case and over a large batch of updating, this save can be very significant.

Optimize repairing connections

---

src/VecSim/algorithms/brute_force/brute_force_multi.h
src/VecSim/algorithms/brute_force/brute_force_single.h
src/VecSim/algorithms/hnsw/hnsw.h
src/VecSim/algorithms/hnsw/hnsw_multi.h
src/VecSim/algorithms/hnsw/hnsw_single.h
src/VecSim/algorithms/hnsw/hnsw_tiered.h
src/VecSim/vec_sim.cpp
src/VecSim/vec_sim.h
src/VecSim/vec_sim_index.h
src/VecSim/vec_sim_interface.h
tests/benchmark/bm_batch_iterator.h
tests/unit/test_bruteforce.cpp
tests/unit/test_bruteforce_multi.cpp
tests/unit/test_hnsw.cpp
tests/unit/test_hnsw_multi.cpp
tests/unit/test_hnsw_tiered.cpp

Add lock/unlock API to reduce locking time in ad-hoc BF computations

---

.github/workflows/event-merge-to-queue.yml
.github/workflows/event-pull_request.yml

Follow-up for #422.
This PR:
1. Adds an option to trigger the CI by marking a PR ready for review.
2. Adds a run name to merge-queue events.

improvements

---

src/VecSim/algorithms/brute_force/brute_force_multi.h
src/VecSim/algorithms/hnsw/hnsw_multi.h

[0.6] Fix label deletion from an unordered map - [MOD-6710]

---

cmake/cpu_features.cmake
src/VecSim/spaces/CMakeLists.txt
src/VecSim/spaces/IP_space.cpp
src/VecSim/spaces/L2_space.cpp
src/VecSim/spaces/space_aux.cpp
src/VecSim/spaces/space_aux.h
tests/unit/test_spaces.cpp

- Update the git tag for `cpu_features`
- Cleanup code as we don't need `M1` protection anymore

Enable cpu_features for Apple silicon

---

.github/codecov.yml
.github/workflows/coverage.yml
.github/workflows/event-pull_request.yml

- Add token
- Add configuration
- Update version

Fix codecov flow

---

cmake/cpu_features.cmake
src/VecSim/spaces/CMakeLists.txt
src/VecSim/spaces/IP_space.cpp
src/VecSim/spaces/L2_space.cpp
src/VecSim/spaces/space_aux.cpp
src/VecSim/spaces/space_aux.h
tests/unit/test_spaces.cpp

[0.6] Enable cpu_features for Apple silicon

---

src/VecSim/spaces/IP_space.cpp
src/VecSim/spaces/IP_space.h
src/VecSim/spaces/L2_space.cpp
src/VecSim/spaces/L2_space.h
src/VecSim/spaces/spaces.cpp
src/VecSim/vec_sim_index.h
tests/unit/test_bruteforce.cpp
tests/unit/test_spaces.cpp

Add tests for the alignment hint calculation (both logic [unit] and when creating an index [flow])

Test alignment decision - [MOD-6998]

---

src/VecSim/spaces/IP/IP_AVX512_FP32.h
src/VecSim/spaces/IP/IP_AVX512_FP64.h
src/VecSim/spaces/IP/IP_AVX_FP32.h
src/VecSim/spaces/IP/IP_AVX_FP64.h
src/VecSim/spaces/IP/IP_SSE_FP32.h
src/VecSim/spaces/IP/IP_SSE_FP64.h
src/VecSim/spaces/L2/L2_AVX512_FP32.h
src/VecSim/spaces/L2/L2_AVX512_FP64.h
src/VecSim/spaces/L2/L2_AVX_FP32.h
src/VecSim/spaces/L2/L2_AVX_FP64.h
src/VecSim/spaces/L2/L2_SSE_FP64.h

Backport of https://github.com/RedisAI/VectorSimilarity/pull/481 to 0.8.7

[0.7] [MOD-7048] - Distance calculations - Add constexpr and use fmadd

---

.github/workflows/event-nightly.yml
.github/workflows/flow-temp.yml
.github/workflows/task-backport_pr.yml
.github/workflows/task-unit-test.yml

Fixed unit-test flow for OSs that don't support node20
Added slack notification on nightly failure
Update backport flow (aligned with RediSearch)

Fix nightly, backport and merge-queue

---

.github/workflows/event-pull_request.yml
.github/workflows/release-drafter.yml
.github/workflows/task-check-docs.yml

Update various action versions, mostly dropping node16 usage

GHA - update action versions

---

.github/workflows/event-pull_request.yml
.github/workflows/release-drafter.yml
.github/workflows/task-check-docs.yml

[0.6] update actions versions

---

.github/workflows/event-pull_request.yml
.github/workflows/release-drafter.yml
.github/workflows/task-check-docs.yml

[0.7] update actions versions

---

.github/workflows/event-merge-to-queue.yml

Add bionic to PR validation on merge-to-queue

---

tests/unit/test_hnsw_tiered.cpp

Until now we had a workaround for index type single and we waited for the connect unreachable feature which we decided not to do. Here we also fix it for multi, not relating to the connect unreachable feature. 

[MOD-6922] Fix flaky test switch modes in tiered index

---

tests/unit/test_hnsw_tiered.cpp

CP flaky switch mode 0.8

---

tests/unit/test_hnsw_tiered.cpp

CP flaky switch mode 0.7

---

.install/ubuntu_24.04.sh
src/VecSim/algorithms/hnsw/graph_data.h
src/python_bindings/bindings.cpp
tests/module/redismodule.h
tests/unit/test_hnsw_parallel.cpp

* add ubuntu2404 install script
* format with clang-format 18
---------
Co-authored-by: alon-reshef <alon.reshef@redis.com>
(cherry picked from commit f08c0515a3e43157f86516cc3ac460c02e24147e)
1. #...
2. MOD...
1. ...
2. ...

Backport-547-to-0.7 

---

.github/workflows/arm.yml
.github/workflows/task-unit-test.yml
.install/centos_linux_7.sh
tests/unit/test_bruteforce_multi.cpp

Change long tests ordering  so we won't get timeout on Valgrind

Adjust long tests for batch iterator in bf_multi + fix checkout in old OSs [0.6]

---

src/VecSim/spaces/IP_space.cpp
tests/module/redismodule.h

in the scope of #562 - format according to ubuntu24

[0.6] format according to ubuntu24

---

src/VecSim/algorithms/hnsw/graph_data.h
src/python_bindings/bindings.cpp
tests/module/redismodule.h
tests/unit/test_hnsw_parallel.cpp

in the scope of #562 - format according to ubuntu24

[0.7] format according to ubuntu24

---

tests/unit/test_hnsw_parallel.cpp

[0.8] Improve HNSW-parallel tests - [MOD-7970]

---

.github/workflows/benchmark.yml
tests/benchmark/benchmarks.sh
tests/benchmark/bm_definitions.h
tests/benchmark/bm_files.sh
tests/benchmark/bm_initialization/bm_basics_initialize_uint8.h
tests/benchmark/bm_initialization/bm_batch_initialize_uint8.h
tests/benchmark/bm_vecsim_index.h
tests/benchmark/data/hnsw_indices/hnsw_indices_all.txt
tests/benchmark/data/hnsw_indices/hnsw_indices_basic_uint8.txt
tests/benchmark/data/scripts/serializer.py
tests/benchmark/data/scripts/uint-fy.py
tests/benchmark/run_files/bm_basics_multi_uint8.cpp
tests/benchmark/run_files/bm_basics_single_uint8.cpp
tests/benchmark/run_files/bm_batch_iterator_multi_uint8.cpp
tests/benchmark/run_files/bm_batch_iterator_single_uint8.cpp
tests/benchmark/types_ranges.h

[8.0] Benchmark uint8 - single&multi 

---

.github/workflows/benchmark-runner.yml
.github/workflows/coverage.yml
.github/workflows/event-pull_request.yml
.github/workflows/task-unit-test.yml
.gitignore
.gitmodules
CMakeLists.txt

Add svs as a git submodule and build the library with it

Add svs submodule

---

.github/workflows/coverage.yml
.github/workflows/event-pull_request.yml

replace coverage flow ami to a machine with a larger disk space.

Increase Codecov machine storage

---

src/VecSim/algorithms/brute_force/brute_force.h
src/VecSim/algorithms/hnsw/hnsw.h
src/VecSim/algorithms/hnsw/hnsw_tiered.h
src/VecSim/info_iterator.cpp
src/VecSim/info_iterator.h
src/VecSim/info_iterator_struct.h
src/VecSim/vec_sim.cpp
src/VecSim/vec_sim.h
src/VecSim/vec_sim_common.h
src/VecSim/vec_sim_index.h
src/VecSim/vec_sim_interface.h
src/VecSim/vec_sim_tiered_index.h
src/python_bindings/bindings.cpp
tests/benchmark/bm_batch_iterator.h
tests/benchmark/bm_common.h
tests/module/memory_test.c
tests/unit/test_allocator.cpp
tests/unit/test_bf16.cpp
tests/unit/test_bruteforce.cpp
tests/unit/test_bruteforce_multi.cpp
tests/unit/test_fp16.cpp
tests/unit/test_hnsw.cpp
tests/unit/test_hnsw_multi.cpp
tests/unit/test_hnsw_parallel.cpp
tests/unit/test_hnsw_tiered.cpp
tests/unit/test_utils.cpp
tests/unit/test_utils.h

[0.8] Refactor Info Report - [MOD-9321]

---

src/VecSim/algorithms/brute_force/brute_force.h
src/VecSim/algorithms/hnsw/hnsw.h
src/VecSim/algorithms/hnsw/hnsw_tiered.h
src/VecSim/info_iterator.cpp
src/VecSim/info_iterator.h
src/VecSim/info_iterator_struct.h
src/VecSim/vec_sim.cpp
src/VecSim/vec_sim.h
src/VecSim/vec_sim_common.h
src/VecSim/vec_sim_index.h
src/VecSim/vec_sim_interface.h
src/VecSim/vec_sim_tiered_index.h
src/python_bindings/bindings.cpp
tests/benchmark/bm_batch_iterator.h
tests/benchmark/bm_common.h
tests/module/memory_test.c
tests/unit/test_allocator.cpp
tests/unit/test_bf16.cpp
tests/unit/test_bruteforce.cpp
tests/unit/test_bruteforce_multi.cpp
tests/unit/test_fp16.cpp
tests/unit/test_hnsw.cpp
tests/unit/test_hnsw_multi.cpp
tests/unit/test_hnsw_parallel.cpp
tests/unit/test_hnsw_tiered.cpp
tests/unit/test_int8.cpp
tests/unit/test_uint8.cpp
tests/unit/unit_test_utils.cpp
tests/unit/unit_test_utils.h

[8.0] Refactor Info Report - [MOD-9321]

---

src/VecSim/spaces/IP_space.cpp
src/VecSim/spaces/L2_space.cpp

[0.8] Fix support of old compiler versions

---

.github/workflows/event-pull_request.yml

1. #...
2. MOD...
1. ...
2. ...

8.0 update event pull req

---

.github/wordlist.txt
README.md

[8.0] [MOD-8365]  Update datatypes and metric support in README (#686)

---

src/VecSim/algorithms/svs/svs_tiered.h

1. #...
2. MOD...
1. ...
2. ...

[SVS] Enforce 'withSet' for tiered XXXQueryImp() calls.

---

src/VecSim/algorithms/svs/svs_tiered.h
tests/unit/test_svs_tiered.cpp

[8.2] [SVS] Fix SVSTiered overwriteVectorAsync and KNNSearchCosine tests
