- src/VecSim/algorithms/hnsw/hnswlib.h
Fix leak in destructor - we need to go over all the possible ids and release their associated nodes data. If some internal ids were deleted and not re-used, `cur_elements_num` is lower than `max_id`. Then, the internal id's upper bound when releasing the index should be `max_id` instead of `cur_elements_num`.
> valgrind fix2

- src/VecSim/algorithms/hnsw/hnswlib.h
- src/VecSim/algorithms/hnsw/hnswlib_c.cpp
- src/VecSim/vec_sim_common.h
- tests/unit/test_hnswlib.cpp
in the case when we delete the index entry point:
if we don't find a neighbor of the entry point to replace it,
we need to check if there is any other vector in the entry point top level,
and only then check the level below.
> Delete enter point bug

- src/VecSim/algorithms/brute_force/vector_block.h
- src/VecSim/algorithms/hnsw/hnswlib.h
- src/VecSim/utils/vec_utils.h
- tests/unit/test_hnswlib.cpp
Deletion of a node in HNSW index is followed by a procedure of repairing edges for other nodes that were pointing to the deleted node. In this procedure, we select neighbours to the repaired node by the heuristics, and compare these to the original set of its neighbours. We assume that these 2 "nodes queues" are sorted in a unified way - by their distance to the repaired node. However, when there is tie, the order of the nodes is undefined, and may result inconsistency when going over the two queues. In some case, we miss a node that is selected to be linked to the repaired node because of that, and it leads to the disconnection of the entire graph. 
In this PR we add a seconder sorting by the id, so that the order of the nodes in the 2 queues is well defined. This also fixes an incorrect …
> Fix HNSW deletion tie bug

- src/VecSim/vec_sim.cpp
- tests/unit/test_allocator.cpp
This PR adds reporting on the memory consumption delta per adding or deleting a vector.
When adding a vector the returned value from `VecSimIndex_AddVector` will be positive int.
When deleting a vector the returned value from `VecSimIndex_DeleteVector` will be negative int.
closes #38
> Add and delete memory reporting

- src/python_bindings/HNSW_iterator_demo.ipynb
> Hnsw batch demo

- src/VecSim/algorithms/brute_force/brute_force.cpp
- src/VecSim/algorithms/brute_force/brute_force.h
- src/VecSim/algorithms/hnsw/hnswlib.h
- src/VecSim/algorithms/hnsw/hnswlib_c.cpp
- src/VecSim/algorithms/hnsw/hnswlib_c.h
- src/VecSim/vec_sim.cpp
- src/VecSim/vec_sim.h
- src/VecSim/vec_sim_common.h
- src/VecSim/vec_sim_index.h
- tests/unit/test_bruteforce.cpp
- tests/unit/test_hnswlib.cpp
Added ResolveParams function to VecSimIndex, including the struct VecSimRawParam that holds a parameter in <string,string> key-value fashion.
Also added tests for hnsw and br indexes ResolveParams.
> Resolve raw params

- pyproject.toml
This allows a longer-tail migration to the latest version as each repository is ready, without breaking individual projects.
> Pinning rltest to the last release prior to redis-py 4 as a requirement

- README.md
benchmarks URL in readme pointing to 404
> fix benchmarks url

- src/VecSim/algorithms/brute_force/brute_force.cpp
- src/VecSim/algorithms/brute_force/brute_force.h
- src/VecSim/algorithms/hnsw/hnsw_wrapper.cpp
- src/VecSim/algorithms/hnsw/hnsw_wrapper.h
- src/VecSim/algorithms/hnsw/hnswlib.h
- src/VecSim/utils/vec_utils.cpp
- src/VecSim/utils/vec_utils.h
- src/VecSim/vec_sim_common.h
- tests/unit/test_bruteforce.cpp
- tests/unit/test_hnswlib.cpp
- tests/unit/test_utils.cpp
This is enabler for `ft.debug` to differentiate between the different modes when testing hybrid query in RediSearch
> Add the search mode to the info fields

- src/VecSim/algorithms/brute_force/bf_batch_iterator.cpp
- src/VecSim/algorithms/brute_force/bf_batch_iterator.h
- src/VecSim/algorithms/brute_force/brute_force.cpp
- src/VecSim/algorithms/brute_force/brute_force.h
- src/VecSim/algorithms/hnsw/hnsw_batch_iterator.cpp
- src/VecSim/algorithms/hnsw/hnsw_batch_iterator.h
- src/VecSim/algorithms/hnsw/hnsw_wrapper.cpp
- src/VecSim/algorithms/hnsw/hnsw_wrapper.h
- src/VecSim/batch_iterator.h
- src/VecSim/vec_sim.cpp
- src/VecSim/vec_sim_index.h
- tests/unit/test_bruteforce.cpp
- tests/unit/test_hnswlib.cpp
This include copying the blob when creating batch iterator (as currently we were relying on external buffer that may change).
Unit tests for Cosine were added to both indexes.
> Normalize query vector in batch search cosine

- src/VecSim/algorithms/brute_force/brute_force.cpp
- src/VecSim/algorithms/hnsw/hnsw_wrapper.cpp
- src/VecSim/vec_sim.cpp
- src/VecSim/vec_sim.h
- src/VecSim/vec_sim_index.h
- tests/unit/test_bruteforce.cpp
- tests/unit/test_hnswlib.cpp
exported normalization function and removed normalization step from `getDistanceFrom` function
> Vecsim normalize

- src/VecSim/algorithms/brute_force/bf_batch_iterator.cpp
- src/VecSim/algorithms/hnsw/hnsw_batch_iterator.cpp
- tests/unit/test_bruteforce.cpp
- tests/unit/test_hnswlib.cpp
In brute force - instead of asserting that we hadn't computed the scores when the number of returned results by the batch iterator is 0, we should assert that the number of returned results by the iterator is 0 if the scores hadn't been computed yet (otherwise, we crash after asking for 0 results).
In HNSW - we should insert the entry point node to the candidates heap only when both the returned results count is 0 and the `top_candidates_extra` queue is empty. Otherwise, we might get that the entry point will be returned twice (if we ask for 0 results, and moved the entry point to the `top_candidates_extra`, and then reinsert the entry point to the candidates).
> Fix bug in batch iterators for the case where batch_size=0

- .circleci/config.yml
- src/VecSim/algorithms/brute_force/brute_force.cpp
- src/VecSim/algorithms/brute_force/brute_force.h
- src/VecSim/algorithms/hnsw/hnsw_wrapper.cpp
- src/VecSim/algorithms/hnsw/hnsw_wrapper.h
- src/VecSim/utils/vec_utils.cpp
- src/VecSim/vec_sim.cpp
- src/VecSim/vec_sim.h
- src/VecSim/vec_sim_common.h
- src/VecSim/vec_sim_index.h
- tests/unit/test_bruteforce.cpp
- tests/unit/test_hnswlib.cpp
Add the HYBRID_BATCHES_TO_ADHOC_BF option the VecSearchMode enum, and set this status when changing from BATCHES to AD-HOC BF after executing batches (for info)
> Update hybrid policy status

- src/VecSim/algorithms/brute_force/brute_force.cpp
- src/VecSim/algorithms/hnsw/hnsw_wrapper.cpp
- src/VecSim/algorithms/hnsw/hnsw_wrapper.h
- src/VecSim/vec_sim_common.h
- tests/unit/test_bruteforce.cpp
- tests/unit/test_hnswlib.cpp
adding a new `blocksize` parameter, to set the number of new vectors we need to allocate memory for when we need to resize the index
> HNSW blocksize param

- src/VecSim/algorithms/hnsw/hnsw_batch_iterator.cpp
- src/VecSim/algorithms/hnsw/hnswlib.h
In this PR I remove the USE_SSE flag as all modern processors supports prefetch commands, including ARM based CPUs.
I also replaced the `_mm_prefetch` command with the more general `__builtin_prefetch` command, that is supported on gcc, clang, intel compiler and arm compiler, for both x86 and ARM.
we used the `_mm_prefetch` with the default flag, so we can use `__builtin_prefetch` with no more parameters but the address we want to prefetch.
prefetch commands were introduced to ARM from version v5te and v6, so this PR will drop support for using the lib binaries on earlier versions, but all the compilers should handle (ignore) `__builtin_prefetch` when compiling on this machines, if we ever want to support them
This PR does not include tests beside passing the ARM build on the CI. we …
> using prefetch on all architectures

- .circleci/config.yml
- cmake/gtest.cmake
- tests/benchmark/bm_basics.cpp
- tests/benchmark/bm_batch_iterator.cpp
- tests/benchmark/data/hnsw_indices.txt
This refactor includes the following:
1. Switch to using query vector from DBPedia test set for the benchmark test cases (instead of random vectors). We load these upon constructing the benchmark class from a file that has been uploaded to s3.
2. Use the same query vectors in every test case, but different vectors in every iteration (rather than using a new random vector in every iteration of every test). 
3. Load HNSW and FLAT indices in the constructor, rather than in the setup method. This saves significant amount of time. Note that google benchmark is creating an instance for every test case class *before* it runs the tests. To reduce the memory usage, we create the base class as a single-tone, and reuse the indices among different test cases (that are guaranteed to run serially).
4. …
> Google benchmark - refactor

- src/VecSim/algorithms/brute_force/brute_force.cpp
- src/VecSim/algorithms/hnsw/hnsw_wrapper.cpp
- src/VecSim/algorithms/hnsw/hnswlib.h
- tests/unit/test_bruteforce.cpp
- tests/unit/test_hnswlib.cpp
* modified resize logic of BF addvector so that the ids2vectors mapping size fits blockSize
* fixed increasing count in case od re-using id, update brute_force_reindexing_same_vector test
* clang format
* HNSWIndex::addVector aligns the capacity to block size, HNSWIndex::deleteVector in case an entire block is removed, the capacity is aligned to blocksize and a decreased by block size, added test for resize cases in hnswlib
* make format
* update size estimation test
* fixed after Alon's review
* clang format
* cahnged hnsw::remove point to return false in case not found,
also changed HNSWIndex::delete vector to return false in this case (before checking if resizing is required) - this covers (hopedully) also empty index case and resizing only when actual deletion happend
* added tests …
> resizing to align blocksize  (#177)

- src/VecSim/algorithms/hnsw/hnsw_wrapper.cpp
- src/VecSim/algorithms/hnsw/hnsw_wrapper.h
- src/VecSim/algorithms/hnsw/hnswlib.h
- src/VecSim/utils/vec_utils.cpp
- src/VecSim/utils/vec_utils.h
- src/VecSim/vec_sim_common.h
- src/python_bindings/bindings.cpp
- tests/benchmark/bm_basics.cpp
- tests/flow/test_hnswlib.py
- tests/unit/test_hnswlib.cpp
- tests/unit/test_utils.cpp
Implement based on option B in the design doc - https://redislabs.atlassian.net/wiki/spaces/DX/pages/2644312347/VecSim+-+Range+query
This includes adding test cases to google benchmark and adding the new `epsilon` parameter to the python bindings (+ using it in flow tests). Also, `epsilon` parameter is now exposed as part of the HNSW index info.
> Range query support for HNSW

- tests/benchmark/CMakeLists.txt
- tests/benchmark/bm_spaces.cpp
- tests/benchmark/bm_spaces_class.cpp
- tests/benchmark/bm_spaces_class.h
* compile bm_saces class without optimizations
* changed names and moved functions
* improved benchmarks definitions
Co-authored-by: DvirDukhan <dvir@redis.com>
> Fixing benchmark run for #175 (#182)

- .circleci/config.yml
updating CI xcode version from 11.6.0 to 11.7.0, which is the only xcode 11 version supported right now
> updating CI xcode version from 11.6.0 to 11.7.0

- src/CMakeLists.txt
- src/VecSim/algorithms/brute_force/bf_batch_iterator.cpp
- src/VecSim/algorithms/brute_force/bf_batch_iterator.h
- src/VecSim/algorithms/brute_force/brute_force.cpp
- src/VecSim/algorithms/brute_force/brute_force.h
- src/VecSim/algorithms/brute_force/brute_force_single.cpp
- src/VecSim/algorithms/brute_force/brute_force_single.h
- src/VecSim/algorithms/brute_force/vector_block.h
- src/VecSim/algorithms/hnsw/hnsw_batch_iterator.cpp
- src/VecSim/algorithms/hnsw/hnsw_wrapper.cpp
- src/VecSim/algorithms/hnsw/hnsw_wrapper.h
- src/VecSim/algorithms/hnsw/hnswlib.h
- src/VecSim/algorithms/hnsw/serialization.cpp
- src/VecSim/info_iterator.h
- src/VecSim/utils/vec_utils.cpp
- src/VecSim/utils/vec_utils.h
- src/VecSim/vec_sim.cpp
- src/VecSim/vec_sim.h
- src/VecSim/vec_sim_common.h
- src/VecSim/vec_sim_index.cpp
- src/VecSim/vec_sim_index.h
- src/VecSim/vec_sim_interface.h
- src/python_bindings/bindings.cpp
- tests/benchmark/bm_basics.cpp
- tests/unit/test_allocator.cpp
- tests/unit/test_bruteforce.cpp
- tests/unit/test_hnswlib.cpp
- tests/unit/test_utils.cpp
* unified types, moved common members to VecSimIndex
* added multi param to vecsimparams and used it
to determine what constructor to call
* generalized brute_force.cpp and moved specifics
* prepared bf batch iterator to support multi
* fixed tests (using only BruteForceIndex_Single)
* update bindings
* changed index creation flow to use factors
* added vecsim interface
to support the coming up templates
* preparing bf_batch_itr for inheritance
* rebase after deleting space interface
* moving `GetDistFunc` to vecsim abstract class
* moves `GetDim` & `setLastSearchMode` to base class
* added `multi` flag to vecsim base
* added label count and is multi to info fields
* review fixes
* generalizing hnsw batch flow
* review improvements
> Inheritance Refactor (#196)

- src/CMakeLists.txt
- src/VecSim/algorithms/brute_force/brute_force.cpp
- src/VecSim/algorithms/brute_force/brute_force_multi.cpp
- src/VecSim/algorithms/brute_force/brute_force_multi.h
- src/VecSim/utils/vecsim_stl.h
- tests/unit/CMakeLists.txt
- tests/unit/test_bruteforce.cpp
- tests/unit/test_bruteforce_multi.cpp
This PR introduces the `BruteForceIndex_Multi` class, which supports multi-value indexing under the same label. Any call to `VecSimIndex_Add` with this instance and an existing label in the index, will result in another vector under the same label. The "delete" function will delete all vectors under the given label.
To create a multi-indexing FLAT instance, use the `.multi` option in `BFParams`.
1. adds a new `BruteForceIndex_Multi` class that supports multi-value indexing with the FLAT algorithm.
> Introducing multi-value indexing to FLAT algorithm

- src/VecSim/spaces/IP/IP.cpp
- src/VecSim/spaces/IP/IP.h
- src/VecSim/spaces/IP_space.cpp
- src/VecSim/spaces/IP_space.h
- src/VecSim/spaces/L2/L2.cpp
- src/VecSim/spaces/L2/L2.h
- src/VecSim/spaces/L2_space.cpp
- src/VecSim/spaces/L2_space.h
- src/VecSim/spaces/spaces.cpp
- src/VecSim/spaces/spaces.h
- tests/unit/test_spaces.cpp
In this PR we added fp64 support to no optimization distance calculation functions.
> Distance calculation functions for doubles - no optimizations

- src/VecSim/algorithms/brute_force/brute_force.h
- src/VecSim/algorithms/brute_force/brute_force_multi.h
- src/VecSim/algorithms/brute_force/brute_force_single.h
- src/VecSim/algorithms/hnsw/hnsw.h
- src/VecSim/algorithms/hnsw/hnsw_factory.cpp
- src/VecSim/algorithms/hnsw/hnsw_multi.h
- src/VecSim/algorithms/hnsw/hnsw_single.h
- src/VecSim/algorithms/hnsw/serialization.cpp
- src/VecSim/algorithms/hnsw/serialization.h
- tests/flow/test_hnswlib.py
- tests/unit/CMakeLists.txt
- tests/unit/test_allocator.cpp
- tests/unit/test_bruteforce.cpp
- tests/unit/test_bruteforce_multi.cpp
- tests/unit/test_hnsw.cpp
- tests/unit/test_hnsw_multi.cpp
This PR implements the multi-value HNSW algorithm. it splits the `hnsw.h` file into `hnsw.h` for the base class and `hnsw_single.h` for the single (regular) case.
1. HNSW index file is now the base class, and hnsw_single and hnsw_multi derive from it.
2. improved the size estimation for HNSW (and modified to support multi-index)
3. "prefer ad-hoc" is changed to check the ratio between the sub-set size and the label count.
> multivalue hnsw - derive hnsw single and multi from base hnsw

- cmake/cpu_features.cmake
Updates https://github.com/google/cpu_features from 0.7.0 to be aligned with current master commit. Removes cpu features tests build warnings
1.Fixes https://github.com/RediSearch/RediSearch/issues/3102
cpu features fetch content
> cpu features latest

- src/VecSim/algorithms/brute_force/brute_force.h
- src/VecSim/algorithms/brute_force/brute_force_multi.h
- src/VecSim/algorithms/brute_force/brute_force_single.h
- src/VecSim/algorithms/hnsw/hnsw.h
- src/VecSim/algorithms/hnsw/hnsw_multi.h
- src/VecSim/algorithms/hnsw/hnsw_single.h
- src/VecSim/utils/vecsim_results_container.h
- tests/flow/test_bruteforce.py
- tests/flow/test_hnswlib.py
- tests/unit/test_bruteforce_multi.cpp
- tests/unit/test_common.cpp
- tests/unit/test_hnsw_multi.cpp
- tests/unit/test_utils.cpp
This PR enables RANGE queries on multi-value HNSW indices.
It also includes a definition for abstract API for results containers (for collecting results while scanning the index), and implementations for two results containers, for single and multi indices.
1. [MOD-3934](https://redislabs.atlassian.net/browse/MOD-3934)
2. [MOD-4280](https://redislabs.atlassian.net/browse/MOD-4280)
1. results container API and implementation
2. HNSW base class
3. HNSW single and multi
> Multi-Value - HNSW - enable range queries

- .circleci/config.yml
- tests/module/memory_test.c
Test was using INT64 as vector's data type which is not supported. Since we began validating the data type, these tests fails on nightly. This PR fixes the tests by using FLOAT64 as vectors data type instead.
> Fix module test in nightly

- .github/workflows/codeql-analysis.yml
- .github/workflows/default.yml
- .github/workflows/default_invoker.yml
- .github/workflows/multi-build.yml
- .github/workflows/ok_to_merge.yml
This PR adds skip for `noci` and `docs` branch as well as adds the `ok to merge` label
> skip on noci

- src/VecSim/spaces/IP_space.cpp
- src/VecSim/spaces/L2_space.cpp
- tests/unit/test_spaces.cpp
Before this PR, for fp64, we swapped between the AVX512F distance calculation function of 2 cases:
1. the dimension is a multiplier of 2, 
or
2. The dimension is bigger than 8 and the residual is smaller than 2
So, for example for dim = 12 ( % 2 == 0 )
We were calculating the first 8 numbers as a batch, and the rest 4 numbers one by one (this will yield the correct result but less optimal than calculating the residual in batches of 2.
for dim = 13 we were taking the first 8 and then calculating the rest in batches of 2, which means that the last batch exceeds the valid dimension.
1. Returning the wrong optimization function when using AVX512 with fp64
1. FP64_GetDistFunc in L2 and …
> fixed get AVX512F functions MOD-4593

- tests/benchmark/bm_files.sh
The bm_files.sh script parameter is now optional.
with no arguments, it downloads all files.
1. The argument passed to the scripts is the git label. In nightly runs, this would be an empty parameter.
1. bm_files.sh
> added default behavior for bm_files script

- src/VecSim/algorithms/brute_force/brute_force.h
- src/VecSim/algorithms/brute_force/brute_force_multi.h
- src/VecSim/algorithms/brute_force/brute_force_single.h
- src/VecSim/algorithms/hnsw/hnsw.h
- src/VecSim/algorithms/hnsw/hnsw_multi.h
- src/VecSim/algorithms/hnsw/hnsw_single.h
- src/VecSim/algorithms/hnsw/hnsw_tiered.h
- src/VecSim/tombstone_interface.h
- src/VecSim/vec_sim.cpp
- src/VecSim/vec_sim_interface.h
- tests/unit/test_allocator.cpp
- tests/unit/test_bruteforce_multi.cpp
- tests/unit/test_hnsw.cpp
- tests/unit/test_hnsw_multi.cpp
- tests/unit/test_hnsw_tiered.cpp
- Remove "unmark deleted" API, as it is currently redundant for our async index
- Let add and delete vector APIs in the index interface to return the number of vectors added/deleted (and take into consideration overwrites).
- Add an `override_allowed` flag to `addVector` interface, so we can enforce that the internal HNSW index within the tiered index will not be able to override existing vectors (rather than creating a delete job in advance).
- Add `indexCapacity()` and `resize()` to index interface and adjust the existing indexes accordingly. Call resize *before* we add new vectors externally in `vec_sim.cpp`
> Refactor add/delete API as an enabler for tiered index

- .github/workflows/benchmark.yml
The `redistimeseries_pass` argument is sent to redisbench-admin export command as raw characters, and when special characters are part of the password token (such as `*`), it may not be read properly. Hence, we turn the argument into a string.
> Stringify password token for benchmarks

- src/VecSim/algorithms/hnsw/hnsw.h
- src/VecSim/algorithms/hnsw/hnsw_tiered.h
- src/VecSim/algorithms/hnsw/hnsw_tiered_tests_friends.h
- src/VecSim/vec_sim_common.h
- src/VecSim/vec_sim_tiered_index.h
- tests/unit/test_hnsw_tiered.cpp
Implement `addVector` for the tiered index, where we **assume that there are no overwrites** (for now). Insertion is done into the flat buffer, the insert job callback that is responsible for adding the vector into HNSW graph is not part of this PR scope.
This includes some refactoring of the tiered index structures - among them, making the `AsyncJob` and its derivatives jobs structs inherit from `VecSimObjectBase`, so we can account for the memory that is allocated for the jobs
> Tiered index add vector MOD-4316

- src/VecSim/algorithms/hnsw/hnsw_tiered.h
- src/VecSim/algorithms/hnsw/hnsw_tiered_tests_friends.h
- src/VecSim/vec_sim_common.h
- src/VecSim/vec_sim_tiered_index.h
- tests/unit/test_hnsw_tiered.cpp
- tests/unit/test_utils.cpp
- tests/unit/test_utils.h
Let the tiered index receive an external opaque index context, and send this context in turn to the submit callback upon submitting a job to be executed asynchronously. The purpose is that the caller would have the option to create a weak reference to the underline index (or the index spec, in RediSearch case) and associate it with the job. When the job is executed, the weak reference is promoted as long as the index has not been deleted. Hence, if the index is deleted while the job is being executed, it is guarded. 
This includes small refactor - moving the pointer to the index to the base `AsyncJob`
> Set an external index context for tiered index - for ownership management MOD-4875

- src/VecSim/algorithms/hnsw/hnsw_tiered.h
Fix mutual exclusion between flat buffer guard and HNSW index data guard by avoiding releasing and reacquiring the flat guard upon index resize (when HNSW index data guard is held)
> Fix deadlock in tiered index async add vector flow

- src/VecSim/algorithms/hnsw/hnsw.h
Fix the bug that causes `replaceEntryPoint` function to hang upon performing a "busy wait" to a candidate that is in process, and should be the new entry point. 
The first reason was that the busy wait loop was optimized by the compiler, and only called once, so if the element is in process when we reached that point, it will hang. The solution is using a volatile variable that enforce the compiler to check if the candidate is in process in every iteration.
The second potential corruption is that we may set MARK_DELETED and unset IN_PROCESS flags simultaneously if an element is done being indexed while it marked as deleted. Then, this includes changing the flags update to be atomic.    
> Fix inf loop bug in replace entry point

- src/VecSim/algorithms/brute_force/brute_force.h
- tests/unit/test_allocator.cpp
- tests/unit/test_bruteforce.cpp
`id_to_label_mapping` in brute force index is a std::vector, and whenever we `resize` it, its capacity is determined according to this container's policy. Then, when we add a block and call for `resize`, the capacity is doubled (rather than increased by block size). The fix is calling `shring_to_fit()` which deallocates unnecessary memory from the container (so its capacity matches its size). 
> Call shrink to fit for id to label mapping in flat index

- src/VecSim/algorithms/brute_force/brute_force.h
- tests/unit/test_allocator.cpp
- tests/unit/test_bruteforce.cpp
Cherry-pick from #362
id_to_label_mapping in brute force index is a std::vector, and whenever we resize it, its capacity is determined according to this container's policy. Then, when we add a block and call for resize, the capacity is doubled (rather than increased by block size). The fix is calling shring_to_fit() which deallocates unnecessary memory from the container (so its capacity matches its size).
> shrink to fit in BF index [CP]

- src/VecSim/algorithms/brute_force/brute_force.h
- src/VecSim/algorithms/brute_force/brute_force_multi.h
- src/VecSim/algorithms/brute_force/brute_force_single.h
- src/VecSim/algorithms/hnsw/hnsw.h
- src/VecSim/algorithms/hnsw/hnsw_tiered.h
- src/VecSim/memory/vecsim_base.h
- src/VecSim/memory/vecsim_malloc.cpp
- src/VecSim/memory/vecsim_malloc.h
- src/VecSim/vec_sim.cpp
- src/VecSim/vec_sim.h
- src/VecSim/vec_sim_common.h
- src/VecSim/vec_sim_index.h
- src/VecSim/vec_sim_interface.h
- src/VecSim/vec_sim_tiered_index.h
- tests/benchmark/bm_vecsim_basics.h
- tests/unit/test_allocator.cpp
- tests/unit/test_bruteforce.cpp
- tests/unit/test_bruteforce_multi.cpp
- tests/unit/test_hnsw.cpp
- tests/unit/test_hnsw_multi.cpp
- tests/unit/test_hnsw_tiered.cpp
- tests/unit/test_utils.cpp
- tests/unit/test_utils.h
This PR refreshes the API functions needed for getting an external job queue submit function and removes the expected "update memory" function and context.
It also changes the `VecSimIndex_AddVector` and `VecSimIndex_DeleteVector`'s API so they return the number of vectors added/deleted (like the C++ API does), instead of the memory delta. the memory consumption should be retrieved using the info function (TBD in another PR).
This PR also moved the ownership of a job to the job queue once it is submitted. This way it's the user's external queue's responsibility to handle leftover jobs after the index itself was deleted. This change is also present in the job queue mock.
Finally, some additional functionality was added to the test utils, such as …
> Tiered HNSW - API update - [MOD-5099]

- src/VecSim/algorithms/hnsw/hnsw_tiered.h
Minor change for optimizing swap jobs execution: hold a `readySwapJobs` counter, and try to acquire HNSW lock for write ONLY IF IT REACHES THE THRESHOLD, rather than when the number of existing swap jobs reaches the threshold. Hence, we save contention over the lock in case there are many swap jobs, but many of them are not ready yet (due to associated repair jobs that haven't finished yet)
> optimize swap jobs handling

- Makefile
- tests/unit/CMakeLists.txt
- tests/unit/test_utils.h
This PR disables FP64 unit tests for indexing algorithms, but keeps distance metric tests.
To trigger the full tests we can call `make unit_test FP_64=1`.
This is done due to long running valgrind tests
> disable fp64 index unit tests by default

- src/VecSim/algorithms/brute_force/brute_force.h
- src/VecSim/algorithms/hnsw/hnsw.h
- src/VecSim/algorithms/hnsw/hnsw_tiered.h
- src/VecSim/utils/vec_utils.cpp
- src/VecSim/utils/vec_utils.h
- src/VecSim/vec_sim.cpp
- src/VecSim/vec_sim.h
- src/VecSim/vec_sim_common.h
- src/VecSim/vec_sim_index.h
- src/VecSim/vec_sim_interface.h
- src/VecSim/vec_sim_tiered_index.h
- src/python_bindings/bindings.cpp
- tests/module/memory_test.c
- tests/unit/test_allocator.cpp
- tests/unit/test_bruteforce.cpp
- tests/unit/test_bruteforce_multi.cpp
- tests/unit/test_hnsw.cpp
- tests/unit/test_hnsw_multi.cpp
- tests/unit/test_hnsw_tiered.cpp
- tests/unit/test_utils.cpp
Split some index meta-data from the unified info struct, and add `VecSimIndex_StaticInfo` API to retrieve these fields alone. The motivation for that is to avoid heavy computation and locking that may occur when calling `VecSimIndex_Info`, since today, in the tiered index, this includes computing the number of labels in the tiered index that includes going over both sub-indices labels-set while holding a lock. So now we can replace the call for `VecSimIndex_Info` upon resolving query params and creating a vector iterator in RediSearch, and remove this bottleneck.
Also,  add additional 2 fields for tiered index - buffer limit and swap jobs threshold.
- [ X ] This PR introduces API changes
> Add static info API

- src/VecSim/algorithms/hnsw/hnsw.h
- src/VecSim/algorithms/hnsw/hnsw_serializer.h
- src/VecSim/algorithms/hnsw/hnsw_serializer_declarations.h
Improve serialization logic for the new HNSW implementation
> Improved serializing code - [MOD-5372]

- tests/unit/test_hnsw_tiered.cpp
The flakiness derived from the fact that we are overriding vectors right after we insert them to the tiered index, then we verify that the backend index contains `2n` vectors where `n` is the number of vectors inserted (and overwritten). We expect to find `2n` vectors since we do not perform GC in the tiered index. However, if we overwrite a vector BEFORE it was moved to the backend HNSW index, it will be erased directly from the flat index and will not be at the backend index eventually, hence the number of vectors in the HNSW is not constant.
The solution - waiting for all vectors to be moved into HNSW after insertion of the first `n` vectors and before overiting starts.  
> Fix flaky test_tiered_hnsw:bufferLimitAsync

- check-format.sh
- src/VecSim/algorithms/brute_force/brute_force_multi.h
- src/VecSim/algorithms/brute_force/brute_force_single.h
- src/VecSim/algorithms/hnsw/hnsw_multi.h
- src/VecSim/algorithms/hnsw/hnsw_multi_batch_iterator.h
- src/VecSim/algorithms/hnsw/hnsw_single.h
- src/VecSim/algorithms/hnsw/hnsw_single_batch_iterator.h
- src/VecSim/algorithms/hnsw/hnsw_tiered.h
- src/VecSim/algorithms/hnsw/visited_nodes_handler.cpp
- src/VecSim/algorithms/hnsw/visited_nodes_handler.h
- src/VecSim/batch_iterator.h
- src/VecSim/memory/vecsim_base.h
- src/VecSim/utils/query_result_utils.h
- src/VecSim/utils/updatable_heap.h
- src/VecSim/utils/vecsim_stl.h
- src/VecSim/vec_sim_index.h
- src/VecSim/vec_sim_interface.h
- src/python_bindings/bindings.cpp
- tests/benchmark/spaces_benchmarks/bm_spaces_class.h
Replacing the `valueToPriority` unordered map of the updatable heap with `valueToNode`.
Instead of having a multimap from priority to values, and an unordered map from value to priority, we will have the same multimap, but with a map from value to its node in the multimap. This way we have less lookup work to do when updating a value's priority.
Additional changes:
1. Replacing empty destructors with default (good practice)
2. Simplifying formatting script
> Improve updatable heap - [MOD-5489]

- tests/benchmark/benchmarks.sh
- tests/benchmark/data/hnsw_indices/hnsw_indices_all.txt
Update benchmark data file list
> Add bf16 and fp16 bm files to  hnsw_indices_all

- tests/unit/test_hnsw_tiered.cpp
Print HNSW graph info upon failure in switchWriteMode flaky test. We expect to validate that the reason for the flaky test is the fact that the graph is not connected.
> Print graph info for debugging flaky switchWriteMode test [MOD-6922]

- .github/workflows/bionic.yml
- .github/workflows/event-merge-to-queue.yml
- .github/workflows/event-nightly.yml
- .github/workflows/flow-temp.yml
- .install/ubuntu_18.04.sh
- cmake/x86_64InstructionFlags.cmake
This PR reinstates support for Ubuntu 18, which was previously removed in [PR #472](https://github.com/RedisAI/VectorSimilarity/pull/472).
The assembler provided by the binutils package in Ubuntu 18 does not support the assembly instructions included in the AVX512BF16 CPU flag. As a result, compilation errors are raised when attempting to compile code that requires this flag.
To avoid these errors, this PR disables the compilation of any code that requires the AVX512BF16 CPU flag when building on Ubuntu 18.
> [MOD-7259] Restore bionic workkflow

- tests/benchmark/spaces_benchmarks/bm_spaces.h
- tests/benchmark/spaces_benchmarks/bm_spaces_bf16.cpp
- tests/benchmark/spaces_benchmarks/bm_spaces_class.h
- tests/benchmark/spaces_benchmarks/bm_spaces_fp16.cpp
- tests/benchmark/spaces_benchmarks/bm_spaces_fp32.cpp
- tests/benchmark/spaces_benchmarks/bm_spaces_fp64.cpp
**Template spaces benchmarks class**
Each type inherits the base class and can modify the conversion method if needed.
This way we can apply conversion for non-native types such as `vecsim_types::float16` and `vecsim_types::bfloat16`, where a c-style cast is not defined.
**Add high dimensions benchmarks**
Another set of spaces benchmarks was added to cover high dimension vectors.
The bm is within the range [900:1000:15]. 
Note that a 32 multiplier exits in this range (dim = 960)
> [MOD-7325] Re-design benchmark class:

- src/VecSim/spaces/IP/IP_AVX2_BF16.h
- src/VecSim/spaces/IP/IP_AVX512_FP16.h
- src/VecSim/spaces/IP/IP_AVX512_FP32.h
- src/VecSim/spaces/IP/IP_AVX512_FP64.h
- src/VecSim/spaces/IP/IP_AVX_FP32.h
- src/VecSim/spaces/IP/IP_AVX_FP64.h
- src/VecSim/spaces/IP/IP_F16C_FP16.h
- src/VecSim/spaces/IP/IP_SSE_FP32.h
- src/VecSim/spaces/IP/IP_SSE_FP64.h
- src/VecSim/spaces/L2/L2_AVX2_BF16.h
- src/VecSim/spaces/L2/L2_AVX512_FP16.h
- src/VecSim/spaces/L2/L2_AVX512_FP32.h
- src/VecSim/spaces/L2/L2_AVX512_FP64.h
- src/VecSim/spaces/L2/L2_AVX_FP32.h
- src/VecSim/spaces/L2/L2_AVX_FP64.h
- src/VecSim/spaces/L2/L2_F16C_FP16.h
- src/VecSim/spaces/L2/L2_SSE_FP64.h
* use `constexpr` when we test the residuals to hint the compiler to evaluate the if expression at compile time.
* AVX512 implicitly supports `fmadd`. use it instead of add+mul. This shouldn't improve performance as we expect the compiler to translate add+mul sequence to fmadd at compile time.
We don't use `fmadd` in `AVX2` since it requires another compilation flag (`FMA`). Using it may degrade users with only `AVX2` to `SSE3`.
> [MOD-7048] - Distance claculations - Add constexpr and use fmadd

- .github/workflows/benchmark.yml
- tests/benchmark/bm_files.sh
- tests/benchmark/data/serializer.py
1. Add workflow dispatcher that allows triggering the benchmarks manually
2. parallelize benchmark files download. Downloading all the benchmarks files takes ~5 min instead of more than 20 min.
> Enhance bm files download and add dispatcher to bm flow

- tests/benchmark/bm_files.sh
bm_files.sh script fails when we pass `bm-spaces` since there is no such file.
Fix that by exit if not one of the expected inputs
> exit if bm_files.sh input is not one of the expected inputs

- .install/ubuntu_20.04.sh
- .install/ubuntu_22.04.sh
- tests/benchmark/spaces_benchmarks/bm_spaces.h
In this PR the spaces benchmarks were changed to cover:
1. high dimensions with at least one dimension satisfying `residual == 0` [900:1000:15]
3. low dimensions with at least one dimension satisfying `residual == 0`  [100:200:15]
4. dimensions common for all types
5. no-residual dimensions, starting from the lowest 
6. all residual possibilities for each type, starting for the minimal dimension supported by all optimizations
Data Type | High Dim | Low Dim | No Residual | Residual Range
-- | -- | -- | -- | --
float16 | 900, 915, ..., 990  |  100, 115, ..., 190 | **32**, 64, 256, 1024  | 513, 514, ... , **543**
bfloat16 | 900, 915, ..., 990 | 100, 115, ..., 190 | **32**, 64, 256, 1024 | 513, 514, ... , **543**
float | 900, 915, ..., 990 | 100, 115, ..., 190 | **16**, 64, 256, 1024 | 513, …
> [MOD-7049] Change bm dimensions

- .github/workflows/benchmark.yml
We now process benchmark's result files in parallel to improve the step duration.
> Parallel upload bm results to grafana

- .github/workflows/flow-temp.yml
- src/VecSim/algorithms/hnsw/hnsw.h
- src/VecSim/algorithms/hnsw/hnsw_serializer.h
- src/VecSim/algorithms/hnsw/hnsw_tiered.h
- src/VecSim/batch_iterator.h
- src/VecSim/memory/vecsim_malloc.cpp
- src/VecSim/memory/vecsim_malloc.h
- src/VecSim/spaces/normalize/normalize_naive.h
- src/VecSim/vec_sim_index.h
- src/VecSim/vec_sim_tiered_index.h
Variable length array (vla) is not part of c standard. Therefor, in this PR all stack arrays with length determined at runtime were replaced with allocations managed by a `unique_ptr` and tracked by the library allocator.
The new allocator methods are:
1. `allocate_aligned_unique`
2. `allocate_unique`
Both generate a `unique_ptr` to the allocated memory with a  `Deleter` to release this allocation at the end of the `unique_ptr` object lifetime.
> [MOD-7297] Replace Variable Length Array on stack with heap allocation

- .github/workflows/benchmark-labeled.yml
- .github/workflows/event-pull_request.yml
- .github/workflows/task-check-docs.yml
Replace pull_request with pull_request_target to enable forked PRs to run our basic flow which includes creating EC2 instance for  coverage flow (forked PRs still required maintainer approval to run)
https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target
> Use pull request target in gha

- tests/unit/test_hnsw_tiered.cpp
This test validates that the newly inserted vector found in the query is the first result when the query is the new vector itself. The latest change in the test was to validate that the distance between the label matching the newly inserted vector and the query vector is zero, if it is not found in the query (since it may be unreachable). This was buggy since it tested the distance between the **result label** to the query rather than the **expected label**
Also, this includes testing directly on HNSW, since this is the purpose of the test (see that vectors were inserted to HNSW in place)
> Fix the fix of flaky switch mode test

- .github/workflows/alpine3.yml
- .github/workflows/flow-temp.yml
- Makefile
- tests/unit/test_hnsw_parallel.cpp
This update addresses an issue where Valgrind hangs when running `HNSWTestParalle`l on x86 machines. The exact cause is unclear but appears related to Valgrind's thread management. By setting the `--fair-sched=yes` flag, Valgrind uses a different algorithm to synchronize threads, potentially avoiding the hang.
- Added a test destructor to free the index to avoid false leak alerts.
- Print neighbors in case the search fails to identify unreachable nodes.
- Use `testing::Test::HasFatalFailure()` to halt tests early if they fail within a subroutine or thread.
- Modified `parallelInsertSearch` to continue running queries until 95% of vectors are indexed, rather than just a single query during indexing.
- Split the previous loop running on` is_multi = [false, true]` into two distinct tests—one …
> [MOD-7474] fix valgrind on linux x86

- Makefile
- tests/unit/test_hnsw_parallel.cpp
* add --fair-sched=yes flag to valgrind
* fix test
*  print neighbours if got unexpected ids. fail the test only after all the result's id's have been checked.
(cherry picked from commit a2478efaf31e1b9dfff254b5f7a6b70f13a91bdc)
1. #...
2. MOD...
1. ...
2. ...
> Backport-525-to-0.8

- .install/ubuntu_24.04.sh
- src/VecSim/algorithms/hnsw/graph_data.h
- src/python_bindings/bindings.cpp
- tests/module/redismodule.h
- tests/unit/test_hnsw_parallel.cpp
`ubuntu-latest` GHA runner image is now ubuntu24.04
This PR aligns the library to support PR workflow on ubutnu24:
1. add ubuntu24 install script
2. format the code according to clang-format-18 version, which is the default version in ubuntu24
> bump up to ubuntu24

- .github/workflows/event-pull_request.yml
use github.event.pull_request.number to give a unique name to the concurrency group in the PR workflow
> [MOD-7981] fix concurrency group name in PR workflow

- tests/unit/test_hnsw_parallel.cpp
Completion for #546 where we added the index guard mechanism to make parallel insertion into HNSW thread safe with respect to data blocks resize that requires exclusive lock.  
Here we add the missing protection to the repair operation with mutual lock while insertion is running.
Also, setting a lower block size in the test to better expose the failure, and apply the common synchronization logic to another parallel test.
> Synchronize properly repair/insert test

- .github/workflows/event-merge-to-queue.yml
- .github/workflows/event-nightly.yml
> Disable old OSs + add manual trigger to merge queue and nightly flows 

- .github/workflows/event-merge-to-queue.yml
- .github/workflows/event-nightly.yml
- src/VecSim/algorithms/hnsw/graph_data.h
- src/python_bindings/bindings.cpp
- tests/module/redismodule.h
- tests/unit/test_hnsw_parallel.cpp
Backpot of #556 + format back to clang 14 (since our basic tests which runs on ubuntu-latest run on Ubuntu is 22 again)
> Remove old OSs [0.8]

- src/VecSim/index_factories/brute_force_factory.cpp
- src/VecSim/index_factories/brute_force_factory.h
- src/VecSim/index_factories/components/components_factory.h
- src/VecSim/index_factories/components/preprocessors_factory.h
- src/VecSim/index_factories/hnsw_factory.cpp
- src/VecSim/index_factories/hnsw_factory.h
- src/VecSim/index_factories/tiered_factory.cpp
- src/VecSim/spaces/computer/preprocessor_container.h
- src/VecSim/vec_sim_index.h
- tests/unit/test_hnsw_tiered.cpp
This PR addresses two bugs affecting the initial size estimation of the tiered index.
Before this fix, the `TieredHNSWFactory::EstimateInitialSize` was responsible for initializing specific members of the `BFParams` struct as follows:
```
bf_params_output.type = hnsw_params.type;
bf_params_output.multi = hnsw_params.multi;
```
However, all other members of `BFParams,` including metric, were left uninitialized, defaulting to zero. As a result, the metric defaulted to `VecSimMetric_L2` the default value for `VecSimMetric.`
This caused the memory size of the brute-force index components to be calculated as if it were a `VecSimMetric_L2` index. Consequently, if the actual metric of the index was `VecSimMetric_Cosine,` the size of the cosine preprocessor was omitted from the estimation.
After …
> [MOD-8244] fix TieredFactory::EstimateInitialSize

- .github/workflows/flow-temp.yml
- src/VecSim/spaces/space_includes.h
There are missing implmnetation for several intrinsincs in gcc < 11 
full list and suggested alternatives for each missing function can be found here:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95483
The missing functions were added in gcc11.
in this PR we override `_mm256_loadu_epi8` with `mm256_maskz_loadu_epi8`, using ~0 mask as recommended by the gcc team.
> Override missing intrinsincs in gcc <11

- src/python_bindings/bindings.cpp
- tests/flow/common.py
- tests/flow/test_bruteforce.py
- tests/flow/test_hnsw.py
- tests/flow/test_hnsw_tiered.py
This pull request introduces flow tests for `VecSimType_INT8` data type.
* Implemented `GeneralTest` class for running common tests on BF and HNSW indices. Currently only used by `TestINT8`.
* Created `TestINT8` class, inherits from `GeneralTest`
* Added support for `VecSimType_INT8` in the `PyHNSWLibIndex`:
* `HNSWIndex::saveIndex`
* `HNSWIndex::checkIntegrity`
* Introduced `create_flat_index` and `create_add_vectors` functions to facilitate the creation and addition of vectors to an index.
* Added a function `create_int8_vectors` to generate INT8 vectors for testing purposes.
* `fp32_expand_and_calc_cosine_dist` takes 2 numpy arrays and converts them to `np.float32` to avoid overflow in distance calculations. 
* Updated `IndexCtx` class to include `type_to_dtype` mapping for various …
> [MOD-8206] INT8 flow tests

- tests/unit/test_hnsw_parallel.cpp
Refactor tests and improve logging on failure, for better understanding a flakiness in one of the tests.
> Improve HNSW-parallel tests - [MOD-7970]

- src/VecSim/index_factories/tiered_factory.h
Add `datasize` to the brute force index params when building a tiered index from a serialized hnsw index file.
> initialize dataSize ion abstractInitParams in tiered factory NewIndex from hnsw file

- pyproject.toml
- tests/flow/test_hnsw_parallel.py
1. Change a class name to follow the `pytest` syntax
2. Bump pytest version to solve deprecation warnings
> Flow test improvements

- pyproject.toml
- tests/flow/test_hnsw_parallel.py
> [0.7] Flow test improvements

- .github/workflows/task-unit-test.yml
1. Remove node16 workaround (not valid anymore)
2. Move artifact name generation to before running any test (so we don't skip running it)
3. Improve job and artifact names
> fix artifact naming

- .github/workflows/benchmark.yml
- tests/benchmark/data/hnsw_indices/hnsw_indices_all.txt
- tests/benchmark/data/hnsw_indices/hnsw_indices_basic_int8.txt
- tests/benchmark/data/scripts/download_dataset.py
- tests/benchmark/data/scripts/serializer.py
- tests/benchmark/run_files/bm_basics_single_int8.cpp
- tests/benchmark/run_files/bm_batch_iterator_single_int8.cpp
This PR change the following:
1.  HNSW serialized dataset to an updated one, containing 1mil vectors - **as preparation for multi - dataset**
2. Structure of python files in benchmarks/data  - **to enable orderly addition of new python files**
3. Download dataset template python file
4. Generate multi dataset from single template python file
5. Add missing int8-single file to serializer.py
6. Add missing batch-iter int8 option to benchmark.yml
> Update int8 single hnsw + structural changes

- .github/workflows/benchmark.yml
- tests/benchmark/benchmarks.sh
- tests/benchmark/bm_files.sh
- tests/benchmark/bm_initialization/bm_basics_initialize_bf16.h
- tests/benchmark/bm_initialization/bm_basics_initialize_fp16.h
- tests/benchmark/bm_initialization/bm_basics_initialize_fp32.h
- tests/benchmark/bm_initialization/bm_basics_initialize_fp64.h
- tests/benchmark/bm_initialization/bm_basics_initialize_int8.h
- tests/benchmark/bm_vecsim_basics.h
- tests/benchmark/data/hnsw_indices/hnsw_indices_all.txt
- tests/benchmark/data/hnsw_indices/hnsw_indices_basic_int8.txt
- tests/benchmark/data/scripts/single_to_multi.py
- tests/benchmark/run_files/bm_basics_multi_int8.cpp
- tests/benchmark/run_files/bm_basics_single_int8.cpp
- tests/benchmark/run_files/bm_batch_iterator_multi_int8.cpp
- tests/benchmark/types_ranges.h
This PR change/adds the following:
- Using the apply function to pass benchmark (BF/HNSW) arguments, enabling iteration over radius and epsilon ranges instead of manually specifying combinations.
- Introducing a benchmark_range template struct for better generalization, with static functions returning appropriate arrays based on index data type (default provided if not specialized for type).
- Adding multi int8 benchmarking with a generated dataset.
- Including a single_to_multi Python script (used for generating the int8 multi dataset) for future  use.
> [MOD-8438] Micro-benchmarks for multi - int8 + benchmark ranges generalization 

- .github/workflows/codeql-analysis.yml
- .github/workflows/flow-temp.yml
- .install/macos.sh
- CMakeLists.txt
CMake 4.0 removes support for versions earlier than 3.5, causing calls to `cmake_minimum_required()` or `cmake_policy()` with older policy versions to issue an error. 
To address this, the for `GoogleTest` has been updated to fetch **version 1.16.0** to ensure the `cmake_minimum_required` call is valid for CMake 3.5 and above, maintaining compatibility with CMake 4.0 and beyond.
> [MOD-9303] Update GoogleTest tag to support CMake 4.0 compatibility

- .install/macos.sh
- CMakeLists.txt
Backport #630 to 0.6
* use googletest  1.16.0
* install coreutils on mac
> [0.6] [MOD-9303] Update GoogleTest tag to support CMake 4.0 compatibility

- .install/macos.sh
- CMakeLists.txt
Backport #630 to 0.7
- use googletest 1.16.0
- install coreutils on mac
> [0.7] [MOD-9303] Update GoogleTest tag to support CMake 4.0 compatibility

- .install/macos.sh
- CMakeLists.txt
Backport #630 to 8.0
* use googletest 1.16.0
* install coreutils on mac
> [8.0] [MOD-9303] Update GoogleTest tag to support CMake 4.0 compatibility

- src/VecSim/spaces/IP/IP_NEON_FP64.h
- src/VecSim/spaces/IP/IP_SVE_FP64.h
- src/VecSim/spaces/IP_space.cpp
- src/VecSim/spaces/L2/L2_NEON_FP64.h
- src/VecSim/spaces/L2/L2_SVE_FP64.h
- src/VecSim/spaces/L2_space.cpp
- src/VecSim/spaces/functions/NEON.cpp
- src/VecSim/spaces/functions/NEON.h
- src/VecSim/spaces/functions/SVE.cpp
- src/VecSim/spaces/functions/SVE.h
- src/VecSim/spaces/functions/SVE2.cpp
- src/VecSim/spaces/functions/SVE2.h
- tests/benchmark/spaces_benchmarks/bm_spaces_fp64.cpp
- tests/unit/test_spaces.cpp
Backport of https://github.com/RedisAI/VectorSimilarity/pull/618 to 0.6.
> [0.6] Beng arm opt f64 - [MOD-9077]

- src/VecSim/CMakeLists.txt
This PR removes the following global compiler flags from the CMake configuration:
```cmake
-march=native -mtune=native
```
These flags were originally introduced in [[#598](https://github.com/RedisAI/VectorSimilarity/pull/598)](https://github.com/RedisAI/VectorSimilarity/pull/598) to enable high-performance execution of the SVS dependency by leveraging the build machine's full CPU capabilities.
However, applying `-march=native` and `-mtune=native` **globally** causes several issues:
* **Cross-device compatibility:** hese flags enforce optimizations based on the build machine's architecture, making the resulting binaries potentially incompatible with machines of different architectures.
* **Conflicts with file-specific flags:** Some files require specific architecture features. For …
> remove flags

- src/VecSim/algorithms/brute_force/brute_force.h
- src/VecSim/algorithms/brute_force/brute_force_multi.h
- src/VecSim/algorithms/brute_force/brute_force_single.h
- src/VecSim/algorithms/hnsw/hnsw.h
- src/VecSim/algorithms/hnsw/hnsw_multi.h
- src/VecSim/algorithms/hnsw/hnsw_single.h
- src/VecSim/algorithms/hnsw/hnsw_tiered.h
- src/VecSim/spaces/computer/preprocessor_container.cpp
- src/VecSim/spaces/computer/preprocessor_container.h
- src/VecSim/spaces/computer/preprocessors.h
- src/VecSim/vec_sim_index.h
- src/VecSim/vec_sim_tiered_index.h
- tests/unit/CMakeLists.txt
- tests/unit/test_bruteforce.cpp
- tests/unit/test_index_test_utils.cpp
- tests/unit/test_int8.cpp
- tests/utils/tests_utils.h
backport  #665 to 8.0
conflict resoultions were related to svs files.
> [8.0] [MOD-9557]  Fix incorrect vector blob size calculation

- src/python_bindings/bindings.cpp
2 issues are handled in this PR:
1- An `abort` was identified while running a test related to `PyBatchIterator`. The abort happened when the test was being shutdown. The error comes from the `deleter`passed to the `PyBatchIterator` `shared_ptr` which captures the `PyIndex`by reference. The problem is that there is no guarantee that the `PyIndex`lifetime will survive the `Iterator`. In that deleter a `mutex` is released (which could be in an invalid state). The solution is to have the `mutex`be wrapped in a shared_ptr that will share the ownership with the `PyBatchIterator` deleter as it captures it by value (incrementing its reference count).
2- Deadlock found on `tests/flow/test_hnsw_parallel.py::test_parallel_insert_batch_search`:
- Thread …
> Solve issues with mutexes while running tests on MacOS M1 

- README.md
Small README improvement that helped me build and run Python tests
1. ...
2. ...
> small README improvement

- .github/workflows/coverage.yml
- .github/workflows/event-pull_request.yml
- .github/workflows/task-unit-test.yml
Print the CPU info in our GHA flows
> add cpu info

- cmake/svs.cmake
- src/VecSim/algorithms/svs/svs.h
- src/VecSim/algorithms/svs/svs_extensions.h
- src/VecSim/algorithms/svs/svs_utils.h
- src/VecSim/index_factories/svs_factory.cpp
- src/VecSim/vec_sim_common.h
- tests/unit/test_svs.cpp
This PR introduces SVS LeanVec index compression integration to VecSim `SVSIndex`.
1. No issues
1. Added SVS LeanVec compression support:
- New template parameter `IsLeanVec` for `SVSIndex` class in *svs.h*
- New `SVSStorageTraits` specialization for `IsLeanVec=true` in *svs_extensions.h*
- `SVSStorageTraits` interface extended by `compute_distance_by_id()` used in `SVSIndex::getDistanceFrom_Unsafe()`
- Added new LeanVec options to `VecSimSvsQuantBits` enum in *vec_sim_common.h*
- Reflect new LeanVec options in *svs_factory.h*
- Added new test to `test_svs.cpp` which constructs `SVSIndex` with different kind of compression/quantization.
> [SVS] Add SVS LeanVec compression support

- src/VecSim/utils/query_result_utils.h
> Allow tolerance for comparing float scores

- src/VecSim/algorithms/svs/svs.h
- src/VecSim/algorithms/svs/svs_utils.h
- src/VecSim/index_factories/svs_factory.cpp
This PR updates SVS Index parameters defaults according to rules:
> These should be the defaults values:
> - alpha=1.2 for L2 and 0.95 for IP and cosine
> - construction_window_size = 200
> - graph_max_degree = 32
> - max_candidate_pool_size = 3 * construction_window_size
> - prune_to = graph_max_degree - 4
> - use_search_history = True
> 
1. #...
2. MOD...
1. SVS Vamna Index
> [SVS] Update SVS Index defaults

- src/VecSim/algorithms/svs/svs.h
- src/VecSim/index_factories/components/components_factory.h
- src/VecSim/index_factories/components/preprocessors_factory.h
- src/VecSim/index_factories/svs_factory.cpp
- src/VecSim/spaces/computer/preprocessor_container.cpp
- src/VecSim/spaces/computer/preprocessor_container.h
- src/VecSim/spaces/computer/preprocessors.h
- src/VecSim/vec_sim_index.h
- tests/unit/test_components.cpp
- tests/unit/test_hnsw_tiered.cpp
- Modified SVS index creation to use` indexCalculator = NULL` in `svs_factory.cpp`
- Replaced `preprocessQueryInPlace` with new `preprocessStorageInPlace` API in `preprocessForBatchStorage`
- Removed: `preprocessQueryInPlace` API (unused functionality)
- Added: New `CreatePreprocessorsContainer` overload to skip `CreatePreprocessorsContainerParams`
- Moved: `CreatePreprocessorsContainerParams` from components factory to `preprocessors_factory.h`
> [MOD-9302] Refactor SVS preprocessing and remove unused preprocessQueryInPlace

- cmake/svs.cmake
This PR includes workaround is the workaround for intel/ScalableVectorSearch issue 148
1. #...
2. MOD...
1. ...
2. ...
> [SVS] Disable SVS AVX512 for x86 platforms only

- src/VecSim/algorithms/svs/svs.h
- src/VecSim/algorithms/svs/svs_batch_iterator.h
- src/VecSim/algorithms/svs/svs_extensions.h
- src/VecSim/algorithms/svs/svs_utils.h
- src/VecSim/index_factories/svs_factory.cpp
- src/VecSim/utils/vec_utils.cpp
- src/VecSim/utils/vec_utils.h
- src/VecSim/vec_sim.cpp
- src/VecSim/vec_sim_common.h
- src/python_bindings/bindings.cpp
- tests/flow/test_svs.py
- tests/unit/test_svs.cpp
- tests/unit/unit_test_utils.cpp
This PR exposes SVS search buffer capacity and LeanVec dimension parameters for better performance tuning. Replace #709 as forked PR cannot enable coverage tests.
1. SVS integration code
> Support SVS search buffer capacity and LeanVec dimension parameters 

- cmake/svs.cmake
- tests/unit/test_svs.cpp
This change includes compatibility issues for Linux OSes with GLIBC prior to v.2.28 including AmazonLinux 2.
Now the minimum supported GLIBC version is 2.26.
This change also includes the workaround for GCC v.11.2, which does not fully support C++20 standard.
1. AmazonLinux 2 has old GLIBC version 2.26 released in August 2017
2. Limited support of C++20 standard in GCC v.11.2
1. ...
2. ...
> [SVS] Add support for GLIBC 2.26 systems and GCC v11.2. E.g. AmazonLinux 2

- src/python_bindings/bindings.cpp
- tests/flow/common.py
- tests/flow/test_svs_tiered.py
This PR adds python flow tests for TieredSVSIndex.
1. #...
2. MOD...
1. ...
2. ...
> [SVS] Add TieredSVSIndex flow tests.

- src/VecSim/algorithms/svs/svs_tiered.h
- tests/unit/test_svs_tiered.cpp
1. Data-racing for SVS index threadpool size - now the SVS threadpool size is always updated under backend index lock
2. Wrong addVector() returning value in case of overwriting vector is being moved by the update job:
If update job moved an updating vector during execution of `SVSTieredIndex::addVector()` it is possible the case when `svs_index->deleteVectors()` returns 0 and `frontendIndex->addVector()` returns 1 even if label exists in the index:
* Initial state: frontend index contains a vector with the label `L` and value `X` (`{L: X}`); backend index is `empty`
* User calls `addVector(L, Y)`
* `addVector()`:
* lock backend index
* call `backend->deleteVector(L)` => `ret = 0`
* unlock backend index
* `<thread suspended>`
* Background update job is …
> [SVS] Fix SVSTieredIndexTestBasic.overwriteVectorAsync test

- .github/workflows/macos.yml
- .install/install_cmake.sh
Due to the change introduced in [Homebrew/brew#20304](https://github.com/Homebrew/brew/pull/20304), Homebrew now prevents installing formulae with the same name. This means that workflows attempting to install a formula already present will fail.
This PR fixes the error message failing macos WF by installing cmake only if it isn’t already present.
> Handle Homebrew conflicts: Install cmake only if not present

- tests/benchmark/bm_common.h
- tests/benchmark/bm_vecsim_basics.h
- tests/benchmark/run_files/bm_basics_multi_fp32.cpp
- tests/benchmark/run_files/bm_basics_single_fp32.cpp
> [0.8] [MOD-11237] Block Size Boundary Oscillation Benchmark (#768)

- src/VecSim/algorithms/brute_force/brute_force.h
> Change indexCapacity to return size instead of capacity

- tests/benchmark/CMakeLists.txt
- tests/unit/CMakeLists.txt
- tests/unit/test_bruteforce_multi.cpp
- tests/unit/test_utils.h
backport #785 to 0.6
Upgrade tests C++ standard to `C++20` to allow using `std::type_identity` feature.
The source code is already using `C++20`, i see no reason not to align the test suite.
> [0.6] [MOD-11651] Fix wrong template type deduction in `GenerateAndAddVector` 

- tests/unit/test_bruteforce_multi.cpp
- tests/unit/test_hnsw_tiered.cpp
- tests/unit/test_utils.h
> [0.7] [MOD-11651] Fix wrong template type deduction in `GenerateAndAddVector`

- tests/unit/test_bruteforce_multi.cpp
- tests/unit/test_hnsw_tiered.cpp
- tests/unit/test_svs_tiered.cpp
- tests/unit/unit_test_utils.h
backport #785 to 8.2
Conflicts due to svs multi feature that is not supported in 8.2
> [8.2] [MOD-11651] Fix wrong template type deduction in `GenerateAndAddVector`

- src/VecSim/index_factories/components/components_factory.h
- src/VecSim/spaces/computer/preprocessors.h
- tests/benchmark/bm_vecsim_index.h
- tests/unit/CMakeLists.txt
- tests/unit/test_quantized_hnsw_disk.cpp
Current build time bottleneck is distance calculation, implement basic
SQ to in memory vectors (and query vector) to reduce data size 4X.
1. New preprocessor: `ScalarQuantizationPreprocessor`
2. `HNSWDiskIndex` in disk benchmark
> MOD-11640 Disk quantized storage
